# Generated by Django 4.1 on 2022-08-21 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contacs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='home.contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='qrcode',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='home.qrcode'),
            preserve_default=False,
        ),
    ]
